version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3001:80
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - 30555:30555
    environment:
      - MONGO_URL=mongo
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017